"""Crypto trading page for the Trading Assistant."""

from datetime import datetime, timezone

import streamlit as st

from trading_assistant.data.crypto import BinanceMarketDataProvider
from trading_assistant.monitoring.crypto_intraday_scanner import (
    CryptoCandidate,
    RobustCryptoIntradayScanner,
)
from trading_assistant.monitoring.signal_journal import SignalJournal
from trading_assistant.ui.theme import inject_responsive_css, page_header, section_header

st.set_page_config(page_title="Crypto Trading", page_icon="🪙", layout="wide")
inject_responsive_css()
page_header(
    "🪙 Crypto Intraday",
    "24/7 market intelligence with locked trade plans and live confirmation.",
    accent="cyan",
)

provider = BinanceMarketDataProvider()
scanner = st.session_state.get("crypto_scanner")
if scanner is None or not isinstance(scanner, RobustCryptoIntradayScanner):
    scanner = RobustCryptoIntradayScanner(provider)
    st.session_state.crypto_scanner = scanner
journal = SignalJournal()


def _render_live_selected_coin(
    selected_symbol: str, locked_candidate: CryptoCandidate
) -> None:
    """Refresh market indicators while keeping the scanned trade plan immutable."""
    try:
        snapshot = scanner.analyze_symbol(selected_symbol, datetime.now(timezone.utc))
    except Exception as error:
        st.error(f"Unable to load live {selected_symbol}: {error}")
        return

    candidate = locked_candidate
    section_header(f"📈 {snapshot.symbol} Live Analysis")
    st.caption(
        f"Live snapshot: {snapshot.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')} · "
        "indicators update every 5 seconds · trade plan changes only on a new scan"
    )

    metric_cols = st.columns(7)
    metric_cols[0].metric("Current Price", f"{snapshot.price:.8g}")
    metric_cols[1].metric("EMA 9", f"{snapshot.ema9:.8g}")
    metric_cols[2].metric("EMA 20", f"{snapshot.ema20:.8g}")
    metric_cols[3].metric("RSI", f"{snapshot.rsi:.1f}")
    metric_cols[4].metric("MACD Hist", f"{snapshot.macd_histogram:.6g}")
    metric_cols[5].metric("RVOL", f"{snapshot.relative_volume:.2f}x")
    metric_cols[6].metric("Momentum", f"{snapshot.momentum_5bar_pct:+.2f}%")

    section_header("🧭 Multi-Timeframe Confirmation")
    timeframe_cols = st.columns(4)
    timeframe_cols[0].metric("5m Supertrend", snapshot.trend_5m)
    timeframe_cols[1].metric("15m Supertrend", snapshot.trend_15m)
    timeframe_cols[2].metric("1H Supertrend", snapshot.trend_1h)
    timeframe_cols[3].metric("Momentum", f"{snapshot.momentum_5bar_pct:+.2f}%")

    section_header("🧩 Confluence Breakdown")
    passed = sum(status for _, status in snapshot.confluence)
    total = len(snapshot.confluence)
    confluence_cols = st.columns(3)
    for index, (name, status) in enumerate(snapshot.confluence):
        with confluence_cols[index % 3]:
            st.write(f"{'✅' if status else '❌'} **{name}**")
    st.caption(
        f"{passed}/{total} live core conditions confirmed · "
        "1H confirmation shown separately"
    )

    level_cols = st.columns(2)
    with level_cols[0]:
        section_header("🟢 Support Levels")
        if snapshot.support_levels:
            for index, level in enumerate(snapshot.support_levels, 1):
                st.write(f"S{index}: **{level:.8g}**")
        else:
            st.info("No confirmed support level below current price.")
    with level_cols[1]:
        section_header("🔴 Resistance Levels")
        if snapshot.resistance_levels:
            for index, level in enumerate(snapshot.resistance_levels, 1):
                st.write(f"R{index}: **{level:.8g}**")
        else:
            st.info("No confirmed resistance level above current price.")

    section_header("🚨 Active Trading Plan")
    if candidate.score >= 75:
        if candidate.direction == "LONG":
            st.success(
                f"🟢 LIVE BUY ALERT — {candidate.symbol} · "
                f"locked entry {candidate.entry:.8g}"
            )
        else:
            st.error(
                f"🔴 LIVE SELL ALERT — {candidate.symbol} · "
                f"locked entry {candidate.entry:.8g}"
            )
        st.caption(
            "Signal generated by the scan. This trade plan remains fixed until "
            "a new scan creates a new plan."
        )
    else:
        st.warning(
            f"🟡 NEAR SETUP — {candidate.symbol} · waiting for confirmation · "
            f"scan entry {candidate.entry:.8g}"
        )

    st.write(candidate.reason)

    plan_cols = st.columns(6)
    plan_cols[0].metric("Signal", candidate.direction)
    plan_cols[1].metric("Scan Score", f"{candidate.score:.0f}/100")
    plan_cols[2].metric("Locked Entry", f"{candidate.entry:.8g}")
    plan_cols[3].metric("Stop Loss", f"{candidate.stop_loss:.8g}")
    plan_cols[4].metric("Target 1", f"{candidate.target_1:.8g}")
    plan_cols[5].metric("Target 2", f"{candidate.target_2:.8g}")

    entry_distance = abs(snapshot.price - candidate.entry) / candidate.entry * 100
    if entry_distance <= 0.25:
        entry_status = "🟢 IDEAL ENTRY ZONE"
    elif entry_distance <= 0.75:
        entry_status = "🟡 NEAR ENTRY — watch price"
    else:
        entry_status = "🟠 EXTENDED — avoid chasing"
    st.markdown(
        f"**Current price vs locked entry:** {entry_status} · "
        f"{entry_distance:.2f}% from scan entry"
    )

    risk_cols = st.columns(2)
    with risk_cols[0]:
        section_header("⚠️ Invalidation")
        st.warning(
            f"{candidate.direction} invalid if price closes beyond "
            f"{candidate.stop_loss:.8g}"
        )
    with risk_cols[1]:
        section_header("🔄 Reversal Watch")
        opposite = "SHORT" if candidate.direction == "LONG" else "LONG"
        st.info(
            f"Watch for {opposite} confirmation if the 5m/15m trend flips "
            "and MACD confirms the opposite direction."
        )


section_header("⚡ Scanner")
scan_col, limit_col = st.columns([3, 1])
with scan_col:
    scan_clicked = st.button(
        "🔎 Scan crypto intraday opportunities",
        type="primary",
        use_container_width=True,
    )
with limit_col:
    scan_limit = st.selectbox("Candidates", [5, 10], index=0)

if scan_clicked:
    with st.spinner("Scanning crypto pairs and ranking intraday setups..."):
        st.session_state.crypto_candidates = scanner.scan(
            datetime.now(timezone.utc), limit=scan_limit
        )

candidates = st.session_state.get("crypto_candidates", ())
if candidates:
    section_header("🔥 Best Crypto Intraday Opportunities")
    st.dataframe(
        [
            {
                "Rank": index,
                "Coin": item.symbol,
                "Signal": item.direction,
                "Type": "CONFIRMED" if item.score >= 75 else "NEAR SETUP",
                "Score": f"{item.score:.0f}/100",
                "Scan Price": f"{item.price:.8g}",
                "Entry": f"{item.entry:.8g}",
                "Stop": f"{item.stop_loss:.8g}",
                "Target 1": f"{item.target_1:.8g}",
                "Target 2": f"{item.target_2:.8g}",
                "R:R": f"1:{item.risk_reward:.0f}",
                "Why": item.reason,
            }
            for index, item in enumerate(candidates, 1)
        ],
        use_container_width=True,
        hide_index=True,
    )

    candidate_options = [item.symbol for item in candidates]
    stored_symbol = st.session_state.get("crypto_selected_symbol")
    if stored_symbol not in candidate_options:
        st.session_state.pop("crypto_selected_symbol", None)

    selected_symbol = st.selectbox(
        "🎯 Select a Coin to Trade",
        candidate_options,
        index=0,
        key="crypto_selected_symbol",
    )
    selected_candidate = next(
        (item for item in candidates if item.symbol == selected_symbol), None
    )
    if selected_candidate is not None:
        st.caption(
            "Live indicators update automatically. Entry, stop and targets remain "
            "locked to the latest scan."
        )

        @st.fragment(run_every="5s")
        def live_selected_coin() -> None:
            _render_live_selected_coin(selected_symbol, selected_candidate)

        live_selected_coin()
    else:
        st.error("The selected coin is no longer available in this scan. Please select again.")
else:
    st.warning("No ranked crypto setup is available yet. Run a scan to populate opportunities.")

section_header("📒 BUY / SELL Alert History")
records = journal.records()
if records:
    st.dataframe(
        [
            {
                "Time": record.timestamp,
                "Coin": record.symbol,
                "Alert": "BUY" if record.direction == "LONG" else "SELL",
                "Alert Price": f"{record.entry:.8g}",
                "Stop Loss": f"{record.stop_loss:.8g}",
                "Target 1": f"{record.target_1:.8g}",
                "Target 2": f"{record.target_2:.8g}",
                "Status": record.status,
                "Score": f"{record.score:.0f}/100",
            }
            for record in reversed(records)
        ],
        use_container_width=True,
        hide_index=True,
    )
else:
    st.info("No BUY/SELL alerts have been recorded yet.")

if scanner.last_scan_count:
    with st.expander("🔧 Crypto scan diagnostics"):
        cols = st.columns(3)
        cols[0].metric("Pairs scanned", scanner.last_scan_count)
        cols[1].metric("Qualified", scanner.last_qualified_count)
        cols[2].metric("Data errors", len(scanner.last_scan_errors))
        for symbol, error in list(scanner.last_scan_errors.items())[:20]:
            st.warning(f"{symbol}: {error}")

st.divider()
section_header("📅 Crypto Swing")
st.info(
    "Crypto Swing is the next module. Crypto Intraday remains independent while "
    "its live scanner is validated."
)
