"""NSE intraday validation dashboard."""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st

from trading_assistant.ui.theme import apply_theme, page_header, section_header

JOURNAL_PATH = Path("reports/nse_signal_journal.csv")

st.set_page_config(
    page_title="NSE Validation",
    page_icon="🧪",
    layout="wide",
    initial_sidebar_state="expanded",
)
apply_theme()


def _load_data() -> pd.DataFrame:
    if not JOURNAL_PATH.exists():
        return pd.DataFrame()
    try:
        frame = pd.read_csv(JOURNAL_PATH)
    except (OSError, pd.errors.EmptyDataError):
        return pd.DataFrame()
    if frame.empty:
        return frame
    numeric = [
        "score",
        "entry",
        "stop_loss",
        "target_1",
        "target_2",
        "risk_reward",
        "exit_price",
        "outcome_r",
    ]
    for column in numeric:
        if column in frame:
            frame[column] = pd.to_numeric(frame[column], errors="coerce")
    for column in ["target_1_achieved", "target_2_achieved", "stop_loss_hit"]:
        if column in frame:
            frame[column] = (
                frame[column].fillna(False).astype(str).str.lower().eq("true")
            )
    frame["timestamp"] = pd.to_datetime(
        frame.get("timestamp"), errors="coerce", utc=True
    )
    return frame.sort_values("timestamp", ascending=False).reset_index(drop=True)


def _status(row: pd.Series) -> str:
    status = str(row.get("status", "OPEN"))
    if status == "TARGET_2_ACHIEVED":
        return "🏆 T2 ACHIEVED"
    if status == "STOP_LOSS_HIT":
        return "🛑 STOP LOSS"
    if status == "INVALIDATED":
        return "⚠️ INVALIDATED"
    if bool(row.get("target_2_achieved", False)):
        return "🏆 T2 ACHIEVED"
    if bool(row.get("target_1_achieved", False)):
        return "🎯 T1 ACHIEVED · OPEN"
    return "🟡 OPEN"


def _table(frame: pd.DataFrame) -> pd.DataFrame:
    table = frame.copy()
    table["Time"] = table["timestamp"].dt.strftime("%d %b %H:%M")
    table["Side"] = table["direction"].map(
        {"BUY": "🟢 BUY", "SELL": "🔴 SELL"}
    ).fillna(table["direction"])
    table["Status"] = table.apply(_status, axis=1)
    for source, target in [
        ("entry", "Entry"),
        ("stop_loss", "SL"),
        ("target_1", "T1"),
        ("target_2", "T2"),
    ]:
        table[target] = table[source].map(lambda value: f"₹{value:.2f}")
    table["Exit"] = table["exit_price"].map(
        lambda value: "—" if pd.isna(value) else f"₹{value:.2f}"
    )
    table["Score"] = table["score"].map(lambda value: f"{value:.0f}")
    table["R:R"] = table["risk_reward"].map(lambda value: f"{value:.2f}R")
    table["T1 Hit"] = table["target_1_achieved"].map(
        lambda value: "✅" if value else "—"
    )
    table["T2 Hit"] = table["target_2_achieved"].map(
        lambda value: "🏆" if value else "—"
    )
    table["SL Hit"] = table["stop_loss_hit"].map(
        lambda value: "🛑" if value else "—"
    )
    table["Outcome"] = table["outcome_r"].map(
        lambda value: "OPEN" if pd.isna(value) else f"{value:+.2f}R"
    )
    return table[
        [
            "Time",
            "symbol",
            "Side",
            "Score",
            "Entry",
            "SL",
            "T1",
            "T2",
            "R:R",
            "T1 Hit",
            "T2 Hit",
            "SL Hit",
            "Status",
            "Exit",
            "Outcome",
        ]
    ].rename(columns={"symbol": "Stock"})


page_header(
    "🧪 NSE Intraday Validation Lab",
    "Accuracy dashboard for signals generated by the live NSE intraday engine.",
    accent="purple",
)

left, right = st.columns([4, 1])
with left:
    st.caption(
        "This page reads the persistent NSE signal journal. "
        "It does not place orders or control the live terminal."
    )
with right:
    if st.button("🔄 Refresh", use_container_width=True):
        st.rerun()

frame = _load_data()

if frame.empty:
    st.info(
        "No NSE validation signals have been recorded yet. "
        "Connect Groww or Upstox and run the NSE Intraday page during market hours."
    )
    st.stop()

closed = frame[frame["outcome_r"].notna()]
wins = closed[closed["outcome_r"] > 0]
losses = closed[closed["outcome_r"] < 0]
t1_count = int(frame["target_1_achieved"].sum())
t2_count = int(frame["target_2_achieved"].sum())
sl_count = int(frame["stop_loss_hit"].sum())
total_r = float(closed["outcome_r"].sum()) if not closed.empty else 0.0
average_r = float(closed["outcome_r"].mean()) if not closed.empty else 0.0
win_rate = len(wins) / len(closed) * 100 if not closed.empty else 0.0
t1_rate = t1_count / len(frame) * 100
t2_rate = t2_count / len(frame) * 100

section_header("📊 Engine Performance")
metrics = st.columns(7)
metrics[0].metric("Alerts", len(frame))
metrics[1].metric("Closed", len(closed))
metrics[2].metric("Open", len(frame) - len(closed))
metrics[3].metric("Win Rate", f"{win_rate:.1f}%")
metrics[4].metric("T1 Hit Rate", f"{t1_rate:.1f}%")
metrics[5].metric("T2 Hit Rate", f"{t2_rate:.1f}%")
metrics[6].metric("Total R", f"{total_r:+.2f}R")

secondary = st.columns(5)
secondary[0].metric("BUY", int((frame["direction"] == "BUY").sum()))
secondary[1].metric("SELL", int((frame["direction"] == "SELL").sum()))
secondary[2].metric("T1 Achieved", t1_count)
secondary[3].metric("T2 Achieved", t2_count)
secondary[4].metric("Stop Loss", sl_count)

section_header("📈 Accuracy Snapshot")
summary = st.columns([1, 1, 2])
with summary[0]:
    st.metric("Winning Trades", len(wins))
with summary[1]:
    st.metric("Losing Trades", len(losses))
with summary[2]:
    if not closed.empty:
        st.progress(
            min(max(win_rate / 100, 0.0), 1.0),
            text=f"Closed-trade win rate: {win_rate:.1f}%",
        )
        st.caption(
            f"Total realized performance: {total_r:+.2f}R · "
            f"Average closed trade: {average_r:+.2f}R"
        )
    else:
        st.caption("Waiting for the first closed NSE validation trade.")

section_header("🏭 Sector Performance")
sector_source = frame.copy()
sector_source["Sector"] = sector_source["symbol"].astype(str).str.upper()
try:
    from trading_assistant.monitoring.sector_scanner import symbol_sector

    sector_source["Sector"] = sector_source["symbol"].map(symbol_sector)
except Exception:
    pass
sector_summary = (
    sector_source.groupby("Sector", dropna=False)
    .agg(
        Alerts=("symbol", "count"),
        Closed=("outcome_r", lambda values: values.notna().sum()),
        Total_R=("outcome_r", "sum"),
    )
    .reset_index()
)
sector_summary["Win Rate"] = sector_source.groupby("Sector")["outcome_r"].apply(
    lambda values: (
        (values.dropna() > 0).mean() * 100 if values.notna().any() else 0.0
    )
).values
sector_summary["Total_R"] = sector_summary["Total_R"].fillna(0.0)
sector_summary = sector_summary.sort_values(
    ["Total_R", "Alerts"], ascending=[False, False]
)
if not sector_summary.empty:
    st.dataframe(
        sector_summary.style.format(
            {"Total_R": "{:+.2f}R", "Win Rate": "{:.1f}%"}
        ),
        use_container_width=True,
        hide_index=True,
    )

section_header("🔎 Filters")
filters = st.columns([2, 1, 1, 1])
with filters[0]:
    stocks = ["All"] + sorted(frame["symbol"].dropna().unique().tolist())
    selected_stock = st.selectbox("Stock", stocks)
with filters[1]:
    selected_side = st.selectbox("Side", ["All", "BUY", "SELL"])
with filters[2]:
    selected_status = st.selectbox(
        "Status",
        ["All", "OPEN", "TARGET_2_ACHIEVED", "STOP_LOSS_HIT", "INVALIDATED"],
    )
with filters[3]:
    min_score = st.number_input(
        "Minimum score", min_value=0, max_value=100, value=0, step=5
    )

filtered = frame.copy()
if selected_stock != "All":
    filtered = filtered[filtered["symbol"] == selected_stock]
if selected_side != "All":
    filtered = filtered[filtered["direction"] == selected_side]
if selected_status != "All":
    filtered = filtered[filtered["status"] == selected_status]
filtered = filtered[filtered["score"] >= min_score]

section_header(f"📋 Signal History · {len(filtered)} records")
if filtered.empty:
    st.warning("No NSE validation records match the selected filters.")
else:
    st.dataframe(
        _table(filtered),
        use_container_width=True,
        hide_index=True,
        height=min(650, 120 + len(filtered) * 35),
    )

section_header("🧭 Validation Rules")
notes = st.columns(3)
notes[0].info("🎯 T1 is recorded as progress while the trade remains open.")
notes[1].success("🏆 T2 is treated as a winning completed validation trade.")
notes[2].warning("🛑 SL is treated as a losing completed validation trade.")

st.download_button(
    "⬇️ Download NSE Validation CSV",
    data=frame.to_csv(index=False).encode("utf-8"),
    file_name="nse_signal_validation.csv",
    mime="text/csv",
)
